# manifests/logoutput-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      containers:
        - name: log-output
          image: log-output:2.6
          ports:
            - containerPort: 3000
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: logoutput-config
                  key: MESSAGE
            - name: PORT
              value: "3000"
            - name: PING_PONG_URL
              value: "http://pingpong-svc:3001/pings"
            - name: PORT
              value: "/usr/src/app/config/information.txt"
          volumeMounts:
            - name: logoutput-config-volume
              mountPath: /usr/src/app/config
              readOnly: true
      volumes:
        - name: logoutput-config-volume
          configMap:
            name: logoutput-config

