apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: page-w-image-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: page-w-image
  template:
    metadata:
      labels:
        app: page-w-image
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: page-w-image-claim
      containers:
        - name: page-output
          image: page_output:2.3
          env:
            - name: TODO_BACKEND_URL
              value: "http://todo-backend-svc:3001"
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/shared

        - name: dl-n-save
          image: dl_n_save:2.3
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/shared

